### PR TITLE
lint files to pass qc check

### PR DESCRIPTION
**Pull request by twhetzel**
I ran `black` and `ruff format` locally from within the repo directory to try to address the failing GH Action qc checks.

### CODE REVIEW

**Comment by hrshdhgd** [comment]
just run `tox` it runs both above and more

**Comment by twhetzel** [comment]
do you mean as `poetry run tox -e format`? this returns an error:
```
ROOT: HandledError| provided environments not found in configuration file:
format
```

Trying `poetry run tox` runs, but there are still linting issues found with `poetry run tox -e lint`


Also, the GitHub Action does not properly exclude the `src/mondolib/datamodels/*` directory.

**Comment by twhetzel** [comment]
There still [linting issues](https://github.com/monarch-initiative/mondolib/actions/runs/8274259511/job/22639346714?pr=10#step:7:48). I am not sure how to fix these. It looks like the empty line above the docstring should be removed, but when I do that it also does not pass linting.

**Comment by hrshdhgd** [comment]
`poetry run tox`

**Pull request merged**
